### ISSUE TITLE
Can't download any Windows ISO. Just get straight to this error:

### ISSUE THREAD

**Issue by Renatula** [gravesoft/msdl#7]
{"Errors":[{"Key":"ErrorSettings.SentinelReject","Value":"Sentinel marked this request as rejected.","Type":9}]}
![Screenshot_20241214_185747](https://github.com/user-attachments/assets/1118e2b2-acd6-4246-8f20-c918f2263468)

**Comment by ave9858** [comment]
Fixed

**Comment by Renatula** [comment]
Sorry, wasn't able to comment recently. 12/21/24, issue still remains. Still get this error.

**Comment by WindowsAddict** [comment]
@Renatula show fresh screenshot

**Comment by Renatula** [comment]
> @Renatula show fresh screenshot

![image](https://github.com/user-attachments/assets/fe9dad5f-59a2-479e-861f-6a455731e3f2)

**Comment by Renatula** [comment]
> > @Renatula show fresh screenshot
> 
> ![image](https://private-user-images.githubusercontent.com/190240770/397930022-fe9dad5f-59a2-479e-861f-6a455731e3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODc3MzksIm5iZiI6MTczNDc4NzQzOSwicGF0aCI6Ii8xOTAyNDA3NzAvMzk3OTMwMDIyLWZlOWRhZDVmLTU5YTItNDc5ZS04NjFmLTZhNDU1NzMxZTNmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMzIzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmMxZjI0ZjIzZTFjZDQzYzM2MTQ4YjNiMmNmMDRjZTE0NDNkZmFkZGE0NWRlMjRlZDNjNGJlYjQ4NzU2Y2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a2fhsJQpvhR6p71aV-EetkoL71MAavzUvWKAVUdF_ng)

getting this when trying to download french iso, when trying to download USA version still get old
![image](https://github.com/user-attachments/assets/acfbfaa9-db5f-4f64-88b0-1d27f0cbeccf)

**Comment by ave9858** [comment]
try now

**Comment by Renatula** [comment]
> try now

![image](https://github.com/user-attachments/assets/7e339089-2d92-43d3-8501-3467108b8930)

**Comment by Renatula** [comment]
> try now

Everything seems to work now. Big thanks!

**Comment by Renatula** [comment]
> try now

Everything seems to work now. Big thanks!
